[tool.poetry]
name = "aoc_2021"
version = "0.1.0"
description = ""
authors = ["Lasse Haffke <lasse@haffke.me>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
